# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-31 20:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity_event', '0002_medium_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextrenderer',
            name='context_hints',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='context',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='medium',
            name='additional_context',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
